### ISSUE TITLE
begin, end date에 관하여

### ISSUE THREAD

**Issue by hwiVeloper** [ChanMinPark/BCNLab_Web_v1#1]
year, month 구분하는 것보다
한번에 입력해서 substr같은 것으로 잘라쓰면 될 것 같아요.

begin_ym
end_ym 등으로 변경하는 것을 제안합니다~

html에 2016-06 이런식으로 input 할 수 있는 element가 존재합니다.

**Comment by ChanMinPark** [comment]
int 형으로 저장해놔서 나중에 list로 출력할 때 정렬 하려고 한건데...
혹시 제안하신 2016-06 이런식으로 입력 받는게 문자열이 아니고 int형으로 저장되는 것이던가
아니면 정렬이 가능한 방법이 있다던가 하면 바꿔도 괜찮을 거 같습니다.
혹시 그럴 수 있는 건가요?

**Comment by hwiVeloper** [comment]
char, Varchar으로 저장될텐데 그것 역시 정렬 가능합니다. 입력하기는 validation check 등을 고려해보았을때 그것이 좀 더 편해보입니다

**Comment by ChanMinPark** [comment]
네, 알겠습니다. varchar로 해서 제안하신 방식으로 가지요 ㅎㅎㅎ
